### PR TITLE
Chore: UI libraries Installation

### PR DESCRIPTION
**Pull request by jazztinecruz**
This pull request is for installing and to setup the Next UI and HeroIcons frontend libraries.

### CODE REVIEW

**Comment by nikkoabucejo** [comment]
@jazztinecruz Can we add a `Providers` components? So that we can store all the providers in one location,

**Comment by jazztinecruz** [comment]
I created that in `/libraries/providers`

**Comment by jazztinecruz** [comment]
> @jazztinecruz Can we add a `Providers` components? So that we can store all the providers in one location,

I created that in /libraries/providers

**Comment by nikkoabucejo** [comment]
> > @jazztinecruz Can we add a `Providers` components? So that we can store all the providers in one location,
> 
> I created that in /libraries/providers

I mean as a components, so that we only to import Providers on the `Root` app/layout.tsx

**Pull request merged**
